name: stock_quote_simple_web
version: 0.0.1
description: >
  An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
transformers:
- $dart2js:
    commandLineOptions: [--minify, --show-package-warnings]
